/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import javax.swing.JPanel;

/**
 *
 * @author SetyV
 */
public class Buscar extends javax.swing.JPanel {

    private int Estado;
    
    public void setEstado(int Estado){
    this.Estado=Estado;
    }
    
    public int getEstado(){
    return this.Estado;
    }
    
    public Buscar() {
        initComponents();
    }
    public void showMe(JPanel jp) {
    jp.setSize(900, 620);
    jp.setLocation(0, 0);
    
    panelCustom.removeAll();
    // Cambia esta línea:
    panelCustom.add(jp, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 610));
    
    panelCustom.revalidate();
    panelCustom.repaint();
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCustom = new javax.swing.JPanel();
        MenuIntroDatos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        botonBuscar = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();

        setMaximumSize(new java.awt.Dimension(900, 620));
        setMinimumSize(new java.awt.Dimension(900, 620));
        setPreferredSize(new java.awt.Dimension(900, 620));

        panelCustom.setBackground(new java.awt.Color(204, 204, 255));
        panelCustom.setForeground(new java.awt.Color(255, 255, 255));
        panelCustom.setAlignmentX(1.0F);
        panelCustom.setAlignmentY(1.0F);
        panelCustom.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panelCustom.setEnabled(false);
        panelCustom.setMaximumSize(new java.awt.Dimension(900, 620));
        panelCustom.setMinimumSize(new java.awt.Dimension(900, 620));
        panelCustom.setName("Maracandacas_Project"); // NOI18N
        panelCustom.setPreferredSize(new java.awt.Dimension(900, 620));
        panelCustom.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MenuIntroDatos.setBackground(new java.awt.Color(51, 51, 51));
        MenuIntroDatos.setMaximumSize(new java.awt.Dimension(328, 294));
        MenuIntroDatos.setMinimumSize(new java.awt.Dimension(328, 294));
        MenuIntroDatos.setName(""); // NOI18N

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Introduzca el NIA:");
        jLabel1.setMaximumSize(new java.awt.Dimension(800, 800));
        jLabel1.setPreferredSize(new java.awt.Dimension(800, 800));

        botonBuscar.setBackground(new java.awt.Color(102, 255, 102));
        botonBuscar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botonBuscar.setText("Buscar");
        botonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarActionPerformed(evt);
            }
        });

        txtBuscar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MenuIntroDatosLayout = new javax.swing.GroupLayout(MenuIntroDatos);
        MenuIntroDatos.setLayout(MenuIntroDatosLayout);
        MenuIntroDatosLayout.setHorizontalGroup(
            MenuIntroDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuIntroDatosLayout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addGroup(MenuIntroDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuIntroDatosLayout.createSequentialGroup()
                        .addGroup(MenuIntroDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, MenuIntroDatosLayout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addComponent(botonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(53, 53, 53))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuIntroDatosLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(103, 103, 103))))
        );
        MenuIntroDatosLayout.setVerticalGroup(
            MenuIntroDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuIntroDatosLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(botonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        panelCustom.add(MenuIntroDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCustom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCustom, javax.swing.GroupLayout.DEFAULT_SIZE, 621, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarActionPerformed
        if(getEstado()==1){
        showMe(new ProfeEliminar());
        }else if (getEstado()==2){
        showMe(new ProfeModificar());
        }
    }//GEN-LAST:event_botonBuscarActionPerformed

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MenuIntroDatos;
    private javax.swing.JButton botonBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel panelCustom;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
