/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author Eliabe
 */
public class GUI_Alumno_Notas extends javax.swing.JPanel {

    private GUI_Menu MainP;
    public int alumnoID;
    private String url = "jdbc:mariadb://localhost:3306/gestion_notas";
    private String user = "root";
    private String password = "alumno";

    public void setAlumnoID(int alumnoID) {
        this.alumnoID = alumnoID;
        ideal.setText("Este es " + alumnoID);
        revalidate();
        repaint();
    }

    /**
     * Creates new form GUI_Alumno_Notas
     */
    public GUI_Alumno_Notas() {
        initComponents();

    }

    public void mostrarNotasAlumnoPorModulo(int idModulo) {
        // Consulta SQL para obtener las notas del alumno en un módulo específico
        String sql = "SELECT nota_1ev, nota_2ev, nota_3ev, nota_final FROM notas "
                + "WHERE id_alumno = ? AND id_modulo = ?";

        try (Connection conn = DriverManager.getConnection(url, user, password); PreparedStatement pstmt = conn.prepareStatement(sql)) {

            // Establecer parámetros
            pstmt.setInt(1, this.alumnoID); // ID del alumno (variable de instancia)
            pstmt.setInt(2, idModulo);      // ID del módulo (parámetro del método)

            try (ResultSet rs = pstmt.executeQuery()) {
                if (rs.next()) {
                    lblFirst.setText(rs.getObject("nota_1ev") != null ? rs.getObject("nota_1ev").toString() : "N/A");
                    lblSecond.setText(rs.getObject("nota_2ev") != null ? rs.getObject("nota_2ev").toString() : "N/A");
                    lblThird.setText(rs.getObject("nota_3ev") != null ? rs.getObject("nota_3ev").toString() : "N/A");
                    lblFinal.setText(rs.getObject("nota_final") != null ? rs.getObject("nota_final").toString() : "N/A");
                } else {
                    JOptionPane.showMessageDialog(null, "Todavia no tienes notas en este Modulo, la culpa es de Elvis");
                }
            }
        } catch (SQLException e) {
            System.err.println("Error al consultar las notas: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelNotas = new javax.swing.JPanel();
        panelNotasBaseEntornosProgra = new javax.swing.JPanel();
        textBBBD = new javax.swing.JLabel();
        textEntornos = new javax.swing.JLabel();
        textProgramacion = new javax.swing.JLabel();
        lblFirst = new javax.swing.JTextField();
        lblSecond = new javax.swing.JTextField();
        lblThird = new javax.swing.JTextField();
        panelNotaFinal = new javax.swing.JPanel();
        textFinal = new javax.swing.JLabel();
        lblFinal = new javax.swing.JTextField();
        lblMateria = new javax.swing.JLabel();
        panelSysdate = new javax.swing.JPanel();
        textSysdate = new javax.swing.JTextField();
        botonVolver = new javax.swing.JButton();
        panelOpciones = new javax.swing.JPanel();
        panelBotones = new javax.swing.JPanel();
        botonTodasMaterias = new javax.swing.JButton();
        botonBBDD = new javax.swing.JButton();
        botonEntornos = new javax.swing.JButton();
        botonProgramacion = new javax.swing.JButton();
        botonLenguajeM = new javax.swing.JButton();
        botonSistemas = new javax.swing.JButton();
        botonInglesd = new javax.swing.JButton();
        ideal = new javax.swing.JLabel();

        setBackground(new java.awt.Color(65, 70, 80));
        setFocusable(false);
        setMaximumSize(new java.awt.Dimension(1500, 778));
        setMinimumSize(new java.awt.Dimension(1500, 778));
        setPreferredSize(new java.awt.Dimension(1400, 770));

        panelNotas.setMaximumSize(new java.awt.Dimension(1212, 800));

        panelNotasBaseEntornosProgra.setLayout(new java.awt.GridLayout(2, 3, 35, 10));

        textBBBD.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        textBBBD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textBBBD.setText("1º evaluación");
        textBBBD.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelNotasBaseEntornosProgra.add(textBBBD);

        textEntornos.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        textEntornos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textEntornos.setText("2º evaluación ");
        textEntornos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelNotasBaseEntornosProgra.add(textEntornos);

        textProgramacion.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        textProgramacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textProgramacion.setText("3º evaluación");
        textProgramacion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelNotasBaseEntornosProgra.add(textProgramacion);

        lblFirst.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        lblFirst.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lblFirst.setText("0.0");
        lblFirst.setFocusable(false);
        lblFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblFirstActionPerformed(evt);
            }
        });
        panelNotasBaseEntornosProgra.add(lblFirst);

        lblSecond.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        lblSecond.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lblSecond.setText("0.0");
        lblSecond.setFocusable(false);
        lblSecond.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblSecondActionPerformed(evt);
            }
        });
        panelNotasBaseEntornosProgra.add(lblSecond);

        lblThird.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        lblThird.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lblThird.setText("0.0");
        lblThird.setFocusable(false);
        lblThird.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblThirdActionPerformed(evt);
            }
        });
        panelNotasBaseEntornosProgra.add(lblThird);

        panelNotaFinal.setLayout(new java.awt.GridLayout(2, 3, 35, 10));

        textFinal.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        textFinal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textFinal.setText("Nota final");
        textFinal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelNotaFinal.add(textFinal);

        lblFinal.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        lblFinal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lblFinal.setText("0.0");
        lblFinal.setFocusable(false);
        lblFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblFinalActionPerformed(evt);
            }
        });
        panelNotaFinal.add(lblFinal);

        lblMateria.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        lblMateria.setText("MATERIA");

        javax.swing.GroupLayout panelNotasLayout = new javax.swing.GroupLayout(panelNotas);
        panelNotas.setLayout(panelNotasLayout);
        panelNotasLayout.setHorizontalGroup(
            panelNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNotasLayout.createSequentialGroup()
                .addGroup(panelNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelNotasLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(panelNotasBaseEntornosProgra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelNotasLayout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(panelNotaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelNotasLayout.createSequentialGroup()
                        .addGap(249, 249, 249)
                        .addComponent(lblMateria)))
                .addGap(50, 50, 50))
        );
        panelNotasLayout.setVerticalGroup(
            panelNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNotasLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(lblMateria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelNotasBaseEntornosProgra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelNotaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        panelSysdate.setLayout(new java.awt.GridBagLayout());

        textSysdate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textSysdate.setText("SYSDATE");
        textSysdate.setFocusable(false);
        panelSysdate.add(textSysdate, new java.awt.GridBagConstraints());

        botonVolver.setBackground(new java.awt.Color(51, 51, 51));
        botonVolver.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        botonVolver.setForeground(new java.awt.Color(255, 255, 255));
        botonVolver.setText("Sair");
        botonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActionPerformed(evt);
            }
        });

        botonTodasMaterias.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        botonTodasMaterias.setText("Todas las materias");

        botonBBDD.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        botonBBDD.setText("Base de datos");
        botonBBDD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBBDDActionPerformed(evt);
            }
        });

        botonEntornos.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        botonEntornos.setText("Entornos de desarrollo");
        botonEntornos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEntornosActionPerformed(evt);
            }
        });

        botonProgramacion.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        botonProgramacion.setText("Programación");
        botonProgramacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonProgramacionActionPerformed(evt);
            }
        });

        botonLenguajeM.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        botonLenguajeM.setText("Lenguaje de marcas");
        botonLenguajeM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLenguajeMActionPerformed(evt);
            }
        });

        botonSistemas.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        botonSistemas.setText("Sistemas informáticos");
        botonSistemas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSistemasActionPerformed(evt);
            }
        });

        botonInglesd.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        botonInglesd.setText("Ingles for Dummies");
        botonInglesd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonInglesdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBotonesLayout = new javax.swing.GroupLayout(panelBotones);
        panelBotones.setLayout(panelBotonesLayout);
        panelBotonesLayout.setHorizontalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonBBDD)
                    .addComponent(botonProgramacion)
                    .addComponent(botonLenguajeM)
                    .addComponent(botonEntornos)
                    .addComponent(botonInglesd)
                    .addGroup(panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(botonTodasMaterias)
                        .addComponent(botonSistemas)))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        panelBotonesLayout.setVerticalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonTodasMaterias)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(botonInglesd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonBBDD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonProgramacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonLenguajeM)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonSistemas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonEntornos)
                .addContainerGap())
        );

        ideal.setText("Hola1");

        javax.swing.GroupLayout panelOpcionesLayout = new javax.swing.GroupLayout(panelOpciones);
        panelOpciones.setLayout(panelOpcionesLayout);
        panelOpcionesLayout.setHorizontalGroup(
            panelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOpcionesLayout.createSequentialGroup()
                .addGroup(panelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelOpcionesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelOpcionesLayout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(ideal)))
                .addContainerGap(9, Short.MAX_VALUE))
        );
        panelOpcionesLayout.setVerticalGroup(
            panelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelOpcionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ideal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(botonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1179, Short.MAX_VALUE)
                .addComponent(panelSysdate, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(panelOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(234, 234, 234)
                .addComponent(panelNotas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelNotas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelSysdate, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(192, 192, 192)
                        .addComponent(panelOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(129, 129, 129))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lblFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblFirstActionPerformed
        this.setBackground(new java.awt.Color(250, 183, 37));
    }//GEN-LAST:event_lblFirstActionPerformed

    private void lblSecondActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblSecondActionPerformed
        this.setBackground(new java.awt.Color(250, 183, 37));
    }//GEN-LAST:event_lblSecondActionPerformed

    private void lblThirdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblThirdActionPerformed
        this.setBackground(new java.awt.Color(250, 183, 37));
    }//GEN-LAST:event_lblThirdActionPerformed

    private void lblFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblFinalActionPerformed
        this.setBackground(new java.awt.Color(250, 183, 37));
    }//GEN-LAST:event_lblFinalActionPerformed

    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed
        SwingUtilities.getWindowAncestor(botonVolver).dispose();
        GUI_Menu mainP = new GUI_Menu();

        mainP.showMe(new GUI_Login());
        mainP.setVisible(true);
    }//GEN-LAST:event_botonVolverActionPerformed

    private void botonInglesdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonInglesdActionPerformed
        mostrarNotasAlumnoPorModulo(6);
    }//GEN-LAST:event_botonInglesdActionPerformed

    private void botonBBDDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBBDDActionPerformed
        mostrarNotasAlumnoPorModulo(1);
    }//GEN-LAST:event_botonBBDDActionPerformed

    private void botonProgramacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonProgramacionActionPerformed
        mostrarNotasAlumnoPorModulo(2);

    }//GEN-LAST:event_botonProgramacionActionPerformed

    private void botonLenguajeMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLenguajeMActionPerformed
        mostrarNotasAlumnoPorModulo(5);

    }//GEN-LAST:event_botonLenguajeMActionPerformed

    private void botonSistemasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSistemasActionPerformed
        mostrarNotasAlumnoPorModulo(3);
    }//GEN-LAST:event_botonSistemasActionPerformed

    private void botonEntornosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEntornosActionPerformed
        mostrarNotasAlumnoPorModulo(3);
    }//GEN-LAST:event_botonEntornosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBBDD;
    private javax.swing.JButton botonEntornos;
    private javax.swing.JButton botonInglesd;
    private javax.swing.JButton botonLenguajeM;
    private javax.swing.JButton botonProgramacion;
    private javax.swing.JButton botonSistemas;
    private javax.swing.JButton botonTodasMaterias;
    private javax.swing.JButton botonVolver;
    private javax.swing.JLabel ideal;
    private javax.swing.JTextField lblFinal;
    private javax.swing.JTextField lblFirst;
    private javax.swing.JLabel lblMateria;
    private javax.swing.JTextField lblSecond;
    private javax.swing.JTextField lblThird;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelNotaFinal;
    private javax.swing.JPanel panelNotas;
    private javax.swing.JPanel panelNotasBaseEntornosProgra;
    private javax.swing.JPanel panelOpciones;
    private javax.swing.JPanel panelSysdate;
    private javax.swing.JLabel textBBBD;
    private javax.swing.JLabel textEntornos;
    private javax.swing.JLabel textFinal;
    private javax.swing.JLabel textProgramacion;
    private javax.swing.JTextField textSysdate;
    // End of variables declaration//GEN-END:variables
}
