/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import javax.swing.JOptionPane;

/**
 *
 * @author Vespertino
 */
public class GUI_Login extends javax.swing.JPanel {

    /**
     * Creates new form Menu1
     */
    public GUI_Login() {
        initComponents();
        setVisible(true);
        setSize(1000,1000);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MenuIntroDatos = new javax.swing.JPanel();
        Usuario = new javax.swing.JLabel();
        Enviar = new javax.swing.JButton();
        olvidePwd = new javax.swing.JButton();
        Contraeña = new javax.swing.JLabel();
        pwdInput = new javax.swing.JPasswordField();
        userInput = new javax.swing.JTextField();
        botonVolver = new javax.swing.JButton();

        setBackground(new java.awt.Color(65, 70, 80));
        setForeground(new java.awt.Color(255, 255, 255));
        setAlignmentX(1.0F);
        setAlignmentY(1.0F);
        setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        setEnabled(false);
        setMaximumSize(new java.awt.Dimension(800, 800));
        setName("Maracandacas_Project"); // NOI18N
        setPreferredSize(new java.awt.Dimension(800, 800));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MenuIntroDatos.setBackground(new java.awt.Color(51, 51, 51));
        MenuIntroDatos.setMaximumSize(new java.awt.Dimension(328, 294));
        MenuIntroDatos.setMinimumSize(new java.awt.Dimension(328, 294));
        MenuIntroDatos.setName(""); // NOI18N

        Usuario.setBackground(new java.awt.Color(0, 0, 0));
        Usuario.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        Usuario.setForeground(new java.awt.Color(255, 255, 255));
        Usuario.setText("Usuario");
        Usuario.setMaximumSize(new java.awt.Dimension(800, 800));
        Usuario.setPreferredSize(new java.awt.Dimension(800, 800));

        Enviar.setBackground(new java.awt.Color(102, 255, 102));
        Enviar.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        Enviar.setForeground(new java.awt.Color(0, 0, 0));
        Enviar.setText("Enviar");
        Enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnviarActionPerformed(evt);
            }
        });

        olvidePwd.setBackground(new java.awt.Color(204, 255, 255));
        olvidePwd.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        olvidePwd.setForeground(new java.awt.Color(0, 0, 0));
        olvidePwd.setText("Olvidé mi contraseña");
        olvidePwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                olvidePwdActionPerformed(evt);
            }
        });

        Contraeña.setBackground(new java.awt.Color(0, 0, 0));
        Contraeña.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        Contraeña.setForeground(new java.awt.Color(255, 255, 255));
        Contraeña.setText("Contraseña");
        Contraeña.setMaximumSize(new java.awt.Dimension(800, 800));
        Contraeña.setPreferredSize(new java.awt.Dimension(800, 800));

        pwdInput.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        pwdInput.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        userInput.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        userInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userInputActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MenuIntroDatosLayout = new javax.swing.GroupLayout(MenuIntroDatos);
        MenuIntroDatos.setLayout(MenuIntroDatosLayout);
        MenuIntroDatosLayout.setHorizontalGroup(
            MenuIntroDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuIntroDatosLayout.createSequentialGroup()
                .addGroup(MenuIntroDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MenuIntroDatosLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(MenuIntroDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Contraeña, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userInput)
                            .addComponent(pwdInput)
                            .addComponent(Enviar, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)))
                    .addGroup(MenuIntroDatosLayout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(olvidePwd, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 83, Short.MAX_VALUE))
        );
        MenuIntroDatosLayout.setVerticalGroup(
            MenuIntroDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuIntroDatosLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userInput, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Contraeña, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pwdInput, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Enviar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(olvidePwd)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        add(MenuIntroDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 460, -1));

        botonVolver.setBackground(new java.awt.Color(51, 51, 51));
        botonVolver.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        botonVolver.setForeground(new java.awt.Color(255, 255, 255));
        botonVolver.setText("Volver");
        botonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActionPerformed(evt);
            }
        });
        add(botonVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 115, 48));
    }// </editor-fold>//GEN-END:initComponents

    private void EnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnviarActionPerformed
        String user = userInput.getText();
        char[] pwd  = pwdInput.getPassword();
        
    }//GEN-LAST:event_EnviarActionPerformed

    private void olvidePwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_olvidePwdActionPerformed
        JOptionPane.showMessageDialog(null, "Debes de pedir cita en IesClaraDelRey.es/citaOnline");
    }//GEN-LAST:event_olvidePwdActionPerformed

    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonVolverActionPerformed

    private void userInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userInputActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Contraeña;
    private javax.swing.JButton Enviar;
    private javax.swing.JPanel MenuIntroDatos;
    private javax.swing.JLabel Usuario;
    private javax.swing.JButton botonVolver;
    private javax.swing.JButton olvidePwd;
    private javax.swing.JPasswordField pwdInput;
    private javax.swing.JTextField userInput;
    // End of variables declaration//GEN-END:variables
}
