/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

/**
 *
 * @author Eliabe
 */
public class GUI_Alumno_NotasGeneral extends javax.swing.JPanel {
    
    /**
     * Creates new form GUI_Alumno_Notas
     */
    public GUI_Alumno_NotasGeneral() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelNotas = new javax.swing.JPanel();
        panelNotasBaseEntornosProgra = new javax.swing.JPanel();
        textBBBD = new javax.swing.JLabel();
        textEntornos = new javax.swing.JLabel();
        textProgramacion = new javax.swing.JLabel();
        textNotaBBDD = new javax.swing.JTextField();
        textNotaEntornos = new javax.swing.JTextField();
        textNotaProgramacion = new javax.swing.JTextField();
        panelNotasLengSistIpe = new javax.swing.JPanel();
        textLenguaje1 = new javax.swing.JLabel();
        textSistemas1 = new javax.swing.JLabel();
        textIPE1 = new javax.swing.JLabel();
        textNotaLenguaje = new javax.swing.JTextField();
        textNotaSistemas = new javax.swing.JTextField();
        textNotaIPE = new javax.swing.JTextField();
        panelSysdate = new javax.swing.JPanel();
        textSysdate = new javax.swing.JTextField();
        botonVolver = new javax.swing.JButton();

        setBackground(new java.awt.Color(65, 70, 80));
        setFocusable(false);
        setMaximumSize(new java.awt.Dimension(1500, 778));
        setMinimumSize(new java.awt.Dimension(1500, 778));
        setPreferredSize(new java.awt.Dimension(1500, 778));

        panelNotas.setMaximumSize(new java.awt.Dimension(1212, 800));

        panelNotasBaseEntornosProgra.setLayout(new java.awt.GridLayout(2, 3, 35, 10));

        textBBBD.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        textBBBD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textBBBD.setText("Base de datos");
        textBBBD.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelNotasBaseEntornosProgra.add(textBBBD);

        textEntornos.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        textEntornos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textEntornos.setText("Entornos de desarrollo");
        textEntornos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelNotasBaseEntornosProgra.add(textEntornos);

        textProgramacion.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        textProgramacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textProgramacion.setText("Programación");
        textProgramacion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelNotasBaseEntornosProgra.add(textProgramacion);

        textNotaBBDD.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        textNotaBBDD.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textNotaBBDD.setText("0.0");
        textNotaBBDD.setFocusable(false);
        textNotaBBDD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNotaBBDDActionPerformed(evt);
            }
        });
        panelNotasBaseEntornosProgra.add(textNotaBBDD);

        textNotaEntornos.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        textNotaEntornos.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textNotaEntornos.setText("0.0");
        textNotaEntornos.setFocusable(false);
        textNotaEntornos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNotaEntornosActionPerformed(evt);
            }
        });
        panelNotasBaseEntornosProgra.add(textNotaEntornos);

        textNotaProgramacion.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        textNotaProgramacion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textNotaProgramacion.setText("0.0");
        textNotaProgramacion.setFocusable(false);
        textNotaProgramacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNotaProgramacionActionPerformed(evt);
            }
        });
        panelNotasBaseEntornosProgra.add(textNotaProgramacion);

        panelNotasLengSistIpe.setLayout(new java.awt.GridLayout(2, 3, 35, 10));

        textLenguaje1.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        textLenguaje1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textLenguaje1.setText("Lenguaje de marcas");
        textLenguaje1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelNotasLengSistIpe.add(textLenguaje1);

        textSistemas1.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        textSistemas1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textSistemas1.setText("Sistemas Informáticos");
        textSistemas1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelNotasLengSistIpe.add(textSistemas1);

        textIPE1.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        textIPE1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textIPE1.setText("IPE");
        textIPE1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelNotasLengSistIpe.add(textIPE1);

        textNotaLenguaje.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        textNotaLenguaje.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textNotaLenguaje.setText("0.0");
        textNotaLenguaje.setFocusable(false);
        textNotaLenguaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNotaLenguajeActionPerformed(evt);
            }
        });
        panelNotasLengSistIpe.add(textNotaLenguaje);

        textNotaSistemas.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        textNotaSistemas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textNotaSistemas.setText("0.0");
        textNotaSistemas.setFocusable(false);
        textNotaSistemas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNotaSistemasActionPerformed(evt);
            }
        });
        panelNotasLengSistIpe.add(textNotaSistemas);

        textNotaIPE.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        textNotaIPE.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textNotaIPE.setText("0.0");
        textNotaIPE.setFocusable(false);
        textNotaIPE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNotaIPEActionPerformed(evt);
            }
        });
        panelNotasLengSistIpe.add(textNotaIPE);

        javax.swing.GroupLayout panelNotasLayout = new javax.swing.GroupLayout(panelNotas);
        panelNotas.setLayout(panelNotasLayout);
        panelNotasLayout.setHorizontalGroup(
            panelNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNotasLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(panelNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelNotasBaseEntornosProgra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelNotasLengSistIpe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        panelNotasLayout.setVerticalGroup(
            panelNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNotasLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(panelNotasBaseEntornosProgra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(panelNotasLengSistIpe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        panelSysdate.setLayout(new java.awt.GridBagLayout());

        textSysdate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textSysdate.setText("SYSDATE");
        textSysdate.setFocusable(false);
        panelSysdate.add(textSysdate, new java.awt.GridBagConstraints());

        botonVolver.setBackground(new java.awt.Color(51, 51, 51));
        botonVolver.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        botonVolver.setForeground(new java.awt.Color(255, 255, 255));
        botonVolver.setText("Volver");
        botonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(botonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1173, Short.MAX_VALUE)
                .addComponent(panelSysdate, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(254, 254, 254)
                .addComponent(panelNotas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelSysdate, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(215, 215, 215)
                .addComponent(panelNotas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(242, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void textNotaBBDDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNotaBBDDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNotaBBDDActionPerformed

    private void textNotaEntornosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNotaEntornosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNotaEntornosActionPerformed

    private void textNotaProgramacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNotaProgramacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNotaProgramacionActionPerformed

    private void textNotaLenguajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNotaLenguajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNotaLenguajeActionPerformed

    private void textNotaSistemasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNotaSistemasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNotaSistemasActionPerformed

    private void textNotaIPEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNotaIPEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNotaIPEActionPerformed

    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonVolverActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonVolver;
    private javax.swing.JPanel panelNotas;
    private javax.swing.JPanel panelNotasBaseEntornosProgra;
    private javax.swing.JPanel panelNotasLengSistIpe;
    private javax.swing.JPanel panelSysdate;
    private javax.swing.JLabel textBBBD;
    private javax.swing.JLabel textEntornos;
    private javax.swing.JLabel textIPE1;
    private javax.swing.JLabel textLenguaje1;
    private javax.swing.JTextField textNotaBBDD;
    private javax.swing.JTextField textNotaEntornos;
    private javax.swing.JTextField textNotaIPE;
    private javax.swing.JTextField textNotaLenguaje;
    private javax.swing.JTextField textNotaProgramacion;
    private javax.swing.JTextField textNotaSistemas;
    private javax.swing.JLabel textProgramacion;
    private javax.swing.JLabel textSistemas1;
    private javax.swing.JTextField textSysdate;
    // End of variables declaration//GEN-END:variables
}
