
package gui;

import java.awt.BorderLayout;
import java.time.LocalDate;
import java.time.LocalDateTime;
import javax.swing.JPanel;

public class ProfeMainV2 extends javax.swing.JFrame {
    private int profeId;
    
    
    public void setProfeID(int profeID){
        this.profeId=profeID;
        lblUsuario.setText(" "+this.profeId);
        revalidate();
        repaint();
    }
    
    public ProfeMainV2() {
        initComponents();
        lblFecha.setText(LocalDate.now().toString());
        
    }
    
public void showMe(JPanel jp) {
    jp.setSize(900, 620);
    jp.setLocation(0, 0);
    
    Prueba.removeAll();
    // Cambia esta línea:
    Prueba.add(jp, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 610));
    
    Prueba.revalidate();
    Prueba.repaint();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelMain1 = new javax.swing.JPanel();
        botonVolver = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        pnlInfo = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Prueba = new javax.swing.JPanel();
        cambioPanel = new javax.swing.JPanel();
        botonAltas = new javax.swing.JButton();
        botonBajas = new javax.swing.JButton();
        botonMod = new javax.swing.JButton();
        botonLista = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelMain1.setMinimumSize(new java.awt.Dimension(920, 780));
        PanelMain1.setPreferredSize(new java.awt.Dimension(920, 780));
        PanelMain1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonVolver.setText("Cerrar Sesion");
        botonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActionPerformed(evt);
            }
        });
        PanelMain1.add(botonVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 750, 142, 38));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("       LOGO (?)");
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(250, 250, 250)));
        PanelMain1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 170, 119));

        pnlInfo.setBackground(new java.awt.Color(50, 130, 130));
        pnlInfo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(30, 30, 30));
        jLabel2.setText("Bienvenido/a, ");
        pnlInfo.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 22, -1, -1));

        lblFecha.setBackground(new java.awt.Color(204, 204, 255));
        lblFecha.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        lblFecha.setForeground(new java.awt.Color(30, 30, 30));
        lblFecha.setText("Aqui va la fecha");
        lblFecha.setOpaque(true);
        pnlInfo.add(lblFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, -1, -1));

        lblUsuario.setBackground(new java.awt.Color(153, 153, 255));
        lblUsuario.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        lblUsuario.setText("Usuario");
        lblUsuario.setOpaque(true);
        pnlInfo.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 120, 30));

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(30, 30, 30));
        jLabel4.setText("Fecha:");
        pnlInfo.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, -1, -1));

        PanelMain1.add(pnlInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 680, 90));

        Prueba.setPreferredSize(new java.awt.Dimension(910, 620));
        Prueba.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cambioPanel.setBackground(new java.awt.Color(40, 130, 70));
        cambioPanel.setMinimumSize(new java.awt.Dimension(910, 620));
        cambioPanel.setPreferredSize(new java.awt.Dimension(910, 610));
        cambioPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonAltas.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        botonAltas.setText("ALTAS");
        botonAltas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAltasActionPerformed(evt);
            }
        });
        cambioPanel.add(botonAltas, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 280, 50));

        botonBajas.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        botonBajas.setText("BAJAS");
        botonBajas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBajasActionPerformed(evt);
            }
        });
        cambioPanel.add(botonBajas, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, 280, 50));

        botonMod.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        botonMod.setText("MODIFICACIONES");
        botonMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModActionPerformed(evt);
            }
        });
        cambioPanel.add(botonMod, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, 280, 50));

        botonLista.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        botonLista.setText("LISTADOS");
        botonLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonListaActionPerformed(evt);
            }
        });
        cambioPanel.add(botonLista, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 470, 280, 50));

        jLabel3.setText("Decripcion del boton, y tal vez los metodos");
        jLabel3.setOpaque(true);
        cambioPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 530, 860, 70));

        jLabel5.setText("Decripcion del boton, y tal vez los metodos");
        jLabel5.setOpaque(true);
        cambioPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 860, 80));

        jLabel6.setText("Decripcion del boton, y tal vez los metodos");
        jLabel6.setOpaque(true);
        cambioPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 860, 80));

        jLabel7.setText("Decripcion del boton, y tal vez los metodos");
        jLabel7.setOpaque(true);
        cambioPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 860, 80));

        Prueba.add(cambioPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 620));

        PanelMain1.add(Prueba, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 910, 620));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelMain1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelMain1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAltasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAltasActionPerformed
         showMe(new ProfeAltas());   // TODO add your handling code here:
    }//GEN-LAST:event_botonAltasActionPerformed

    private void botonListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonListaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonListaActionPerformed

    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed
        showMe(cambioPanel);
    }//GEN-LAST:event_botonVolverActionPerformed

    private void botonBajasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBajasActionPerformed
        Buscar buscar = new Buscar();
        buscar.setEstado(1);
        showMe(buscar);
    }//GEN-LAST:event_botonBajasActionPerformed

    private void botonModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonModActionPerformed
        Buscar buscar = new Buscar();
        buscar.setEstado(2);
        showMe(buscar);
    }//GEN-LAST:event_botonModActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProfeMainV2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProfeMainV2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProfeMainV2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProfeMainV2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProfeMainV2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelMain1;
    private javax.swing.JPanel Prueba;
    private javax.swing.JButton botonAltas;
    private javax.swing.JButton botonBajas;
    private javax.swing.JButton botonLista;
    private javax.swing.JButton botonMod;
    private javax.swing.JButton botonVolver;
    private javax.swing.JPanel cambioPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPanel pnlInfo;
    // End of variables declaration//GEN-END:variables
}
