/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Types;

/**
 *
 * @author SetyV
 */
public class ProfeAltas extends javax.swing.JPanel {
private Connection connection;
    /**
     * Creates new form ProfeAltas
     */
    public ProfeAltas() {
        initComponents();
    }

    public void insertarAlumnoCompleto() {
        
        String nombre= txtNombre.getText();
        String apellidos=txtApellido.getText();
        String edad=txtEdad.getText();
        String numeroAlumno=txtNia.getText();
        String idCiclo= txtCiclo.getText();
        String curso=txtCurso.getText();
        String fechaMatricula=txtFecha.getText();
        int numero = (int)Math.random()*100;
        String usuario=txtNombre.getText()+numero+".alumno";
        String contrasena="484ac397cb407ab7aad776f0663f8c85";
      
        String sqlAlumno = "INSERT INTO Alumno (nombre, apellidos, edad, numero_alumno, "
                + "id_ciclo, curso, fecha_matricula, usuario_a, contrasena_a) "
                + "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)";
        
        try (Connection conn = DriverManager.getConnection("jdbc:mariadb://localhost:3306/gestion_notas", "root", "alumno")) {
            conn.setAutoCommit(false); // Iniciar transacción
            int idAlumno;
            // Validar campos obligatorios
            if (nombre == null || apellidos == null || numeroAlumno == null || 
                curso == null || fechaMatricula == null || usuario == null || contrasena == null) {
                throw new SQLException("Campos obligatorios faltantes");
            }

            try (PreparedStatement pstmtAlumno = conn.prepareStatement(sqlAlumno, Statement.RETURN_GENERATED_KEYS)) {
                // Insertar alumno
                pstmtAlumno.setString(1, nombre);
                pstmtAlumno.setString(2, apellidos);
                pstmtAlumno.setString(3, edad);
                pstmtAlumno.setString(4, numeroAlumno);
                pstmtAlumno.setString(5, idCiclo);
                pstmtAlumno.setString(6, curso);
                pstmtAlumno.setString(7, fechaMatricula);
                pstmtAlumno.setString(8, usuario);
                pstmtAlumno.setString(9, contrasena);

                int affectedRows = pstmtAlumno.executeUpdate();
                
                if (affectedRows == 0) {
                    throw new SQLException("Error al insertar alumno");
                }
            try (ResultSet rs = pstmtAlumno.getGeneratedKeys()) {
                    if (rs.next()) {
                        idAlumno = rs.getInt(1);
                    } else {
                        throw new SQLException("No se pudo obtener el ID del alumno");
                    }
                }
            }
           
                
            conn.commit(); // Confirmar transacción
            System.out.println("Datos insertados correctamente");
            
        } catch (SQLException e) {
            System.err.println("Error en la inserción: " + e.getMessage());
            try {
                if (connection != null) connection.rollback();
            } catch (SQLException ex) {
                System.err.println("Error en rollback: " + ex.getMessage());
            }
        }
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelji = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtEdad = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtNia = new javax.swing.JTextField();
        txtCiclo = new javax.swing.JTextField();
        txtCurso = new javax.swing.JTextField();
        txtFecha = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        botonValidar = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(900, 620));
        setPreferredSize(new java.awt.Dimension(910, 620));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelji.setBackground(new java.awt.Color(60, 170, 50));
        panelji.setPreferredSize(new java.awt.Dimension(910, 540));

        jLabel7.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(30, 30, 30));
        jLabel7.setText("Nombre:");

        jLabel8.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(30, 30, 30));
        jLabel8.setText("Apellidos:");

        jLabel9.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(30, 30, 30));
        jLabel9.setText("Edad:");

        jLabel11.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(30, 30, 30));
        jLabel11.setText("NIA:");

        jLabel13.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(30, 30, 30));
        jLabel13.setText("Ciclo:");

        jLabel15.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(30, 30, 30));
        jLabel15.setText("Curso:");

        jLabel16.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(30, 30, 30));
        jLabel16.setText("Fecha Matricula:");

        txtEdad.setText("jTextField1");

        txtNombre.setText("jTextField1");

        txtNia.setText("jTextField1");

        txtCiclo.setText("jTextField1");

        txtCurso.setText("jTextField1");

        txtFecha.setText("jTextField1");

        txtApellido.setText("jTextField1");

        javax.swing.GroupLayout paneljiLayout = new javax.swing.GroupLayout(panelji);
        panelji.setLayout(paneljiLayout);
        paneljiLayout.setHorizontalGroup(
            paneljiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneljiLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(paneljiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneljiLayout.createSequentialGroup()
                        .addGroup(paneljiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel11)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 424, Short.MAX_VALUE)
                        .addGroup(paneljiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel15)
                            .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(107, 107, 107))
                    .addGroup(paneljiLayout.createSequentialGroup()
                        .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(paneljiLayout.createSequentialGroup()
                        .addGroup(paneljiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCiclo, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNia, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(110, 110, 110))))
        );
        paneljiLayout.setVerticalGroup(
            paneljiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneljiLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(paneljiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneljiLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel16)
                        .addGap(12, 12, 12)
                        .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paneljiLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNia, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel13)
                        .addGap(7, 7, 7)
                        .addComponent(txtCiclo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(101, Short.MAX_VALUE))
        );

        add(panelji, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 4, -1, -1));

        botonValidar.setBackground(new java.awt.Color(153, 153, 255));
        botonValidar.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        botonValidar.setText("VALIDAR");
        botonValidar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonValidarActionPerformed(evt);
            }
        });
        add(botonValidar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, 900, 70));
    }// </editor-fold>//GEN-END:initComponents

    private void botonValidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonValidarActionPerformed
        insertarAlumnoCompleto();
        
        
    }//GEN-LAST:event_botonValidarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonValidar;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel panelji;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCiclo;
    private javax.swing.JTextField txtCurso;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtNia;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
